//export const FETCH_CATEGORY_REQUEST : string = 'FETCH_CATEGORY_REQUEST';
//export const FETCH_CATEGORY_SUCCESS : string = 'FETCH_CATEGORY_SUCCESS';
//export const FETCH_CATEGORY_ERROR : string = 'FETCH_CATEGORY_ERROR';
//export const FETCH_SHOPPINGLIST_REQUEST : string = "FETCH_SHOPPINGLIST_REQUEST";
//export const FETCH_SHOPPINGLIST_SUCCESS  = "FETCH_SHOPPINGLIST_SUCCESS";
//export const FETCH_SHOPPINGLIST_ERROR: string = "FETCH_SHOPPINGLIST_ERROR";


export enum ActionTypeKeys {
    FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST",
    FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS",
    FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR",
    FETCH_SHOPPINGLIST_REQUEST = "FETCH_SHOPPINGLIST_REQUEST",
    FETCH_SHOPPINGLIST_SUCCESS = "FETCH_SHOPPINGLIST_SUCCESS",
    FETCH_SHOPPINGLIST_ERROR = "FETCH_SHOPPINGLIST_ERROR",
}